### PR TITLE
fix(MultiCascader): fix load async data error in inline mode 

### LINKED ISSUE #3014: When MultiCascader is in inline mode, loading async data not working.
### What version of rsuite are you using?

latest

### What version of React are you using?

latest

### What version of TypeScript are you using (if any)?

any

### What browser are you using?

Chrome

### Describe the Bug

When MultiCascader is in inline mode, loading async data can't display the children's data.

image

Cause: https://github.com/rsuite/rsuite/blob/main/src/MultiCascader/MultiCascader.tsx#L257

### Expected Behavior

display children's data

### To Reproduce

https://codesandbox.io/s/serene-stitch-vzkteu?file=/index.js

### PR DESCRIPTION
**Pull request by superman66**
Closes #3014

### CODE REVIEW

File: src/MultiCascader/MultiCascader.tsx [hunk 1]
```diff
@@ -254,7 +254,7 @@ const MultiCascader: PickerComponent<MultiCascaderProps> = React.forwardRef(
               node.loading = false;
               node[childrenKey] = data;
 
-              if (targetRef.current) {
+              if (targetRef.current || inline) {
```
Comment (simonguo) [inline src/MultiCascader/MultiCascader.tsx:257]: React Hook useCallback has a missing dependency: 'inline'. Either include it or remove the dependency array

**Review by simonguo — CHANGES_REQUESTED** [review]

**Review by simonguo — APPROVED** [review]
