### PR TITLE
fix(DateRangePicker): fix lifecycle for Picker Toggle

### LINKED ISSUE #3073: [DateRangePicker] can't automatically focus the right month panel with `onEnter`
### What version of rsuite are you using?

5.26.1

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.9

### What browser are you using?

Chrome

### Describe the Bug

use DateRangePicker with controlled value & props.onEnter, open picker, onEnter fired but the panel didn't focus on the right panel
Screenshot 2023-02-21 at 11 07 11

### Expected Behavior

focus on the right month panel

### To Reproduce

https://codesandbox.io/s/recursing-booth-45ynmh?file=/src/index.js

### PR DESCRIPTION
**Pull request by MarvelSQ**
### Description
fix picker components with `PickerToggleTrigger`, with {onEnter,onExited,...} props set, the inner life cycle couldn't fire.

### Affected Components

- [x] AutoComplete
- [x] Cascader
- [x] CheckPicker
- [x] CheckTreePicker
- [x] DatePicker
- [x] DateRangePicker
- [x] InputPicker
- [x] MultiCascader
- [x] SelectPicker
- [x] TreePicker

Fixes #3073

### CODE REVIEW

**Review by SevenOutman — CHANGES_REQUESTED** [review]
Please add a test case that verifies case in #3073 is fixed

File: src/DateRangePicker/test/DateRangePickerSpec.tsx [hunk 1]
```diff
@@ -884,6 +884,33 @@ describe('DateRangePicker', () => {
...
+      useEffect(() => {
+        setValue([new Date(2022, 10, 1), new Date(2022, 11, 1)]);
+      }, []);
+      return <DateRangePicker value={value} onChange={setValue} onEnter={onEnterSpy} />;
+    };
+    const { getByRole } = render(<App />);
+
+    fireEvent.click(getByRole('combobox'));
+
+    const dialog = getByRole('dialog');
```
Comment (SevenOutman) [inline src/DateRangePicker/test/DateRangePickerSpec.tsx:901]: Use `screen.getByRole` as `eslint-plugin-testing-library` suggests https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/prefer-screen-queries.md

File: src/DateRangePicker/test/DateRangePickerSpec.tsx [hunk 2]
```diff
@@ -884,6 +884,33 @@ describe('DateRangePicker', () => {
...
+
+    const firstMonthPanelTitle =
+      '.rs-calendar[index="0"] .rs-calendar-header-month-toolbar .rs-calendar-header-title';
+    const secondMonthPanelTitle =
+      '.rs-calendar[index="1"] .rs-calendar-header-month-toolbar .rs-calendar-header-title';
+
+    assert.equal(dialog.querySelector(firstMonthPanelTitle)?.textContent, 'Nov 2022');
+    assert.equal(dialog.querySelector(secondMonthPanelTitle)?.textContent, 'Dec 2022');
+  });
+
```
Comment (SevenOutman) [inline src/DateRangePicker/test/DateRangePickerSpec.tsx:913]: Use `expect` assertions, e.g. 

```js
expect(...).to.have.text('Nov 2022')
```

File: src/DateRangePicker/test/DateRangePickerSpec.tsx [hunk 3]
```diff
@@ -884,6 +884,33 @@ describe('DateRangePicker', () => {
     ).to.have.length(2);
   });
 
+  it('Should focus on the right month', () => {
```
Comment (SevenOutman) [inline src/DateRangePicker/test/DateRangePickerSpec.tsx:887]: Wrap this case with `describe("Issue #3074")`

File: src/DateRangePicker/test/DateRangePickerSpec.tsx [hunk 4]
```diff
@@ -884,6 +884,33 @@ describe('DateRangePicker', () => {
...
+    const App = () => {
+      const [value, setValue] = useState<[Date, Date] | null>([new Date(), new Date()]);
+      useEffect(() => {
+        setValue([new Date(2022, 10, 1), new Date(2022, 11, 1)]);
+      }, []);
+      return <DateRangePicker value={value} onChange={setValue} onEnter={onEnterSpy} />;
+    };
+    const { getByRole } = render(<App />);
+
+    fireEvent.click(getByRole('combobox'));
```
Comment (SevenOutman) [inline src/DateRangePicker/test/DateRangePickerSpec.tsx:899]: Use `rerender` (whenever possible) to update props passed to DateRangePicker.

https://testing-library.com/docs/react-testing-library/api/#rerender

**Review by SevenOutman — CHANGES_REQUESTED** [review]

**Review by SevenOutman — APPROVED** [review]
