### PR TITLE
fix(docs): wrong menuToggle style in RTL direction

### LINKED ISSUE #3221: When the RTL switch is turned on, the style width of the "close menu" button is abnormal.
### What version of rsuite are you using?

5.34.1

### What version of React are you using?

--

### What version of TypeScript are you using (if any)?

--

### What browser are you using?

Chrome

### Describe the Bug

image

link: [https://rsuitejs.com/components/overview/](https://rsuitejs.com/components/overview/)

When the RTL switch is turned on, the style width of the "close menu" button is abnormal.

### Expected Behavior

Expected behavior: The "close menu" button should display normally when the RTL switch is turned on.

### To Reproduce

If it is confirmed that this is a bug, I am willing to do my best to fix it.

### PR DESCRIPTION
**Pull request by leon-fong**
fix #3221

### CODE REVIEW

File: docs/components/TopLevelNav/TopLevelNav.tsx [hunk 1]
```diff
@@ -134,16 +139,28 @@ const TopLevelNav = React.forwardRef((props: TopLevelNavProps, ref: React.Ref<HT
...
+    showSubmenu ? (
+      <AngleRight />
+    ) : (
+      <AngleLeft />
+    )
+  ) : showSubmenu ? (
+    <AngleLeft />
+  ) : (
+    <AngleRight />
+  );
```
Comment (simonguo) [inline docs/components/TopLevelNav/TopLevelNav.tsx:152]: Nesting ternary expressions can make code more difficult to understand.

https://eslint.org/docs/latest/rules/no-nested-ternary#rule-details

**Review by simonguo — CHANGES_REQUESTED** [review]

File: docs/components/TopLevelNav/TopLevelNav.tsx [hunk 2]
```diff
@@ -134,16 +139,24 @@ const TopLevelNav = React.forwardRef((props: TopLevelNavProps, ref: React.Ref<HT
     }
   };
 
+  const ArrowIcon = () => {
+    if (rtl) {
+      return showSubmenu ? <AngleRight /> : <AngleLeft />;
+    } else {
+      return showSubmenu ? <AngleLeft /> : <AngleRight />;
+    }
+  };
```
Comment (simonguo) [inline docs/components/TopLevelNav/TopLevelNav.tsx:148]: `ArrowIcon` is a function component, and in React, you cannot define another component within a component. You should define it outside the `TopLevelNav` component, otherwise, every time `TopLevelNav` renders, it will cause `ArrowIcon` to be redefined and recreated.

**Review by simonguo — CHANGES_REQUESTED** [review]

File: docs/components/TopLevelNav/TopLevelNav.tsx (hunk 2 above)
Comment (leon-fong) [reply docs/components/TopLevelNav/TopLevelNav.tsx]: Thank you for your advice. However, I would like to use the useMemo hook instead. Maybe the useMemo hook can help reduce the amount of code.

**Comment by SevenOutman** [comment]
Looks like the button is still getting stretched shortly during the stylesheet loading

https://github.com/rsuite/rsuite/assets/8225666/ac8f6aa5-7581-4be9-97f6-9699e5a3f7f4

**Review by SevenOutman — APPROVED** [review]
LGTM now, thanks @leon-fong!
