### PR TITLE
fix(TreePicker,CheckTreePicker): fix value being cleared internally when value is controlled

### LINKED ISSUE #2784: Checktreepicker bug? Preset selected value can't be removed. Checkbox misses up
### What version of rsuite are you using?

5.19

### What version of React are you using?

18.2

### What version of TypeScript are you using (if any)?

_No response_

### What browser are you using?

_No response_

### Describe the Bug

<CheckTreePicker defaultExpandAll value={['pages-fragments']} data={data} style={{ width: 280 }} />
image
image
Cancel uncheck the checkboxes, but the "fragments" is not removed.
image
besides, all the checkboxes are uncheckable.....

### Expected Behavior

_No response_

### To Reproduce

_No response_

### PR DESCRIPTION
**Pull request by superman66**
## Problem
If the value is controlled, the developer should handle all the `value`. 
When clicking the clean icon, the checktreepicker will remove all values internally, whether value controlled or not.

## Solution
When clicking the clean icon, if the value is controlled, CheckTreePicker shouldn't remove all values.

Closes #2784

### CODE REVIEW

File: src/CheckTreePicker/test/CheckTreePickerSpec.js [hunk 1]
```diff
@@ -639,4 +639,24 @@ describe('CheckTreePicker', () => {
...
+  });
+
+  it('Should persist value when click clean button and value is controlled', () => {
+    const ref = React.createRef();
+    const screen = render(<CheckTreePicker ref={ref} defaultOpen data={data} value={['Master']} />);
+
+    fireEvent.click(screen.getByLabelText('Clear'));
+    expect(
+      ref.current.target.querySelector('.rs-picker-toggle-value .rs-picker-value-item').textContent
+    ).to.equal('Master (All)');
```
Comment (simonguo) [inline src/CheckTreePicker/test/CheckTreePickerSpec.js:660]: The DOM can be obtained without relying on `ref`.
```suggestion
    expect(screen.getByRole('combobox')).to.text('Master (All)1');
```

File: src/TreePicker/test/TreePickerSpec.js [hunk 2]
```diff
@@ -556,4 +557,24 @@ describe('TreePicker', () => {
     assert.doesNotThrow(() => JSON.stringify(onSelectSpy.firstCall.args[0]));
     assert.doesNotThrow(() => JSON.stringify(renderTreeNodeSpy.firstCall.args[0]));
   });
+
+  it('Should remove all value when click clean button and value is unControlled', () => {
+    const ref = React.createRef();
+    const screen = rtlRender(
```
Comment (simonguo) [inline src/TreePicker/test/TreePickerSpec.js:563]: `rtl` is ambiguous and can be changed to testRender.

**Review by simonguo — CHANGES_REQUESTED** [review]
There are file conflicts that need to be resolved

**Review by simonguo — APPROVED** [review]
