### PR TITLE
Fixes #727

### LINKED ISSUE #727: RTL Support | Drawer Placement Problem
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.11` |
| `rsuite` | `4.1.1` |

### What is the expected behavior?

In the Drawer component, the direction should be **automatically** flipped without having to touch the code.

Direction does not work as expected.

### What is the current behavior?
this.toggleDrawer('left')  opens the drawer from the **left**. 
changing to **RTL** should cause the same code to open the Drawer from the **right**

### What are the steps to reproduce?
create a drawer with default settings, or specify placement as left. change the **dir** of the page to **RTL** the drawer will behave exactly similar to **LTR** case

### PR DESCRIPTION
**Pull request by MohammadYounes**
This PR depends on https://github.com/rsuite/rsuite.github.io/pull/161

### CODE REVIEW

File: src/Modal/Modal.tsx [hunk 1]
```diff
@@ -108,8 +108,10 @@ class Modal extends React.Component<ModalProps, ModalState> {
       bodyStyles: React.CSSProperties;
     } = {
       modalStyles: {
-        paddingRight: bodyIsOverflowing && !modalIsOverflowing ? getScrollbarSize() : 0,
-        paddingLeft: !bodyIsOverflowing && modalIsOverflowing ? getScrollbarSize() : 0
+        [doc.dir !== 'rtl' ? 'paddingRight' : 'paddingLeft']:
+          bodyIsOverflowing && !modalIsOverflowing ? getScrollbarSize() : 0,
+        [doc.dir !== 'rtl' ? 'paddingLeft' : 'paddingRight']:
+          !bodyIsOverflowing && modalIsOverflowing ? getScrollbarSize() : 0
       },
```
Comment (simonguo) [inline src/Modal/Modal.tsx]: In actual development, some development engineers will set the rtl property on the body tag.  So,
```js
(document.body.getAttribute('dir') || doc.dir) !=='rtl'
```
Or, add an `isRTL` method.
```js
function isRTL() {
  return (
    typeof window !== 'undefined' && (document.body.getAttribute('dir') || document.dir) === 'rtl'
  );
}
```

Comment (MohammadYounes) [reply src/Modal/Modal.tsx]: @simonguo The recommendation is to add `dir="rtl"` to the html tag. See: 
* https://www.w3.org/International/questions/qa-html-dir
* https://www.w3.org/International/questions/qa-bidi-css-markup 

Anyway, we can also read the effective direction:

```js
typeof window !== 'undefined' && window.getComputedStyle(document.body).direction === 'rtl';
```

Which gives the freedom of setting the direction via `dir` attribute or `direction` style on either `body` or `html` node.
