### PR TITLE
fix(Nav.Menu): open with hover trigger in Navbar

### LINKED ISSUE #2431: Dropdown's hover trigger doesn't work inside Navbar
### What version of rsuite are you using?

5.7.0

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

_No response_

### What browser are you using?

Edge, Chrome

### Describe the Bug

Setting `trigger` event to "hover" for `Dropdown` (or `Nav.Dropdown`, which extends the former) doesn't work inside `Navbar`. But if Dropdown is placed outside Navbar, then it works just fine.

At first, I thought it doesn't work because of Next.js. But after some more tests, this bug doesn't seem to related to Next.js at all. In the sandbox, you will see that I reproduce the bug without Next.js

### Expected Behavior

I supposed that `trigger="hover"` should work anywhere, outside and inside of Navbar (or any other component).

### To Reproduce

I've placed two identical Dropdown menus with one inside and one outside the Navbar.

If you change `Dropdown` and `Dropdown.Item` to `Nav.Dropdown` and `Nav.Dropdown.Item`, you'll see that the result is the same and that Nav.Dropdown works properly even when placed outside Navbar.

https://codesandbox.io/s/peaceful-einstein-gns64t

### LINKED ISSUE #2720: Navbar > Nav > Nav.Menu open by hovering of mouse
### What problem does this feature solve?
I have to click menu if I want to see menu's items now
Sometimes we want to show my navbar that can be opened by hovering of a mouse.

### What does the proposed API look like?
If i want to see items in menu, I should just click menu. but I wish menu has hovering feature so when it has hovering feature, it doesn't have arrow icon. when I make a mouse move to menu section, menu will be opened automatically

### PR DESCRIPTION
**Pull request by SevenOutman**
Fix #2431 
Fix #2720

### CODE REVIEW

File: src/Disclosure/Disclosure.tsx [hunk 1]
```diff
@@ -83,6 +83,7 @@ const Disclosure: DisclosureComponent = React.memo((props: DisclosureProps) => {
 
   const onMouseEnter = useCallback(
     (event: React.MouseEvent<HTMLElement>) => {
+      console.log('mouseenter');
```
Comment (simonguo) [inline src/Disclosure/Disclosure.tsx:86]: Logs not removed

**Review by simonguo — CHANGES_REQUESTED** [review]

File: src/Disclosure/Disclosure.tsx (hunk 1 above)
Comment (SevenOutman) [reply src/Disclosure/Disclosure.tsx]: Removed now

**Review by simonguo — APPROVED** [review]
