### PR TITLE
fix(CheckTreePicker): fix duplicated key when data changed (#2486)

### LINKED ISSUE #2486: CheckTreePicker does not update correctly
### What version of rsuite are you using?

5.11

### What version of React are you using?

16.8 - 18

### What version of TypeScript are you using (if any)?

_No response_

### What browser are you using?

Chrome, Edge

## Issue
It seems that the CheckTreePicker(CTP for short) component does not update its internal state properly when the data attribute is changed.
## My Case 
I have a custom filter for a tree, based on an additional attribute, so it makes sense to have a separate selector instead of custom filtering everything on the CTP. Before I filter everything is working correctly, but when I reassign the data attribute and try to pick an item I am getting duplicated key error and in the selected list I can see two same items instead of one(ex. two Node 7 items, even tho there is only one in the tree).

### Expected Behavior

To not have a duplicated key issue when changing the data attribute

### To Reproduce

# Steps to reproduce: 
- render CTP with initial data value
- reassign data value with filtered/rearranged value
- select an item -> leads to duplicated key error

Sandbox link - https://codesandbox.io/s/cranky-davinci-11s578?file=/src/App.tsx

### PR DESCRIPTION
**Pull request by superman66**
When node in data changes position, it's equivalent to changing the data. And selected this node again. Will getting duplicated key error in selected list.
image

Fix #2486

### CODE REVIEW

File: src/CheckTreePicker/test/CheckTreePickerSpec.js [hunk 1]
```diff
@@ -611,4 +612,40 @@ describe('CheckTreePicker', () => {
...
+    const mockRenderValue = (values, checkedItems, selectedElement) => {
+      checkItems = checkedItems;
+      return selectedElement;
+    };
+    const ref = React.createRef();
+    render(<TestApp ref={ref} renderValue={mockRenderValue} />);
+
+    ReactTestUtils.act(() => {
+      ref.current.setTreeData(changedMockData);
+    });
```
Comment (SevenOutman) [inline src/CheckTreePicker/test/CheckTreePickerSpec.js:641]: Use `rerender` function to re-render the component with new props.

```jsx
const { rerender } = render(<Component prop={value} />);

rerender(<Component prop={newValue} />);
```

Comment (SevenOutman) [inline src/CheckTreePicker/test/CheckTreePickerSpec.js:641]: Use `rerender` function to re-render the component with new props.

```jsx
const { rerender } = render(<Component prop={value} />);

rerender(<Component prop={newValue} />);
```

File: src/CheckTreePicker/test/CheckTreePickerSpec.js [hunk 2]
```diff
@@ -611,4 +612,36 @@ describe('CheckTreePicker', () => {
...
+  it('Should not has duplicated key when data changed', () => {
+    const TestApp = React.forwardRef((props, ref) => {
+      const pickerRef = React.useRef();
+      React.useImperativeHandle(ref, () => {
+        return {
+          picker: pickerRef.current
+        };
+      });
+      return <CheckTreePicker ref={pickerRef} {...props} open />;
+    });
```
Comment (SevenOutman) [inline src/CheckTreePicker/test/CheckTreePickerSpec.js:625]: Redundant wrapping. Render `<CheckTreePicker>` directly

**Review by SevenOutman — CHANGES_REQUESTED** [review]

**Review by SevenOutman — APPROVED** [review]
